name = "mitrokit-ventures"
compatibility_date = "2026-02-22"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SITE_URL = "https://mitrokit-ventures.denis2s-projects.workers.dev"
